# ConfigMap for API URLs and Redis/Database Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-config
data:
  AUTH_SERVICE_URL: "https://service.district12.xyz/auth"
  VITE_AUTH_API_URL: "https://service.district12.xyz/auth"
  VITE_PAYMENT_API_URL: "https://service.district12.xyz/pay"
  VITE_DOWNLOAD_API_URL: "https://service.district12.xyz/down"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  # POSTGRES_HOST: "template-pg-do-user-18003520-0.g.db.ondigitalocean.com"
  # POSTGRES_PORT: "25060"
  # POSTGRES_DB: "defaultdb"
  # POSTGRES_USER: "doadmin"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: QVZOU19XdW5kSDhpM2hIdFZJblRLZFhr