# Horizontal Pod Autoscaler for ticket-service
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ticket-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tick12-ticket-deploy
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80